server:
  port: 8083
spring:

  application:
    name: PRODUCT_INVENTORY_MANAGEMENT
  datasource:
    url: jdbc:postgresql://localhost:5432/product_inventory?
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
